In [4]:
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("tableau donnés: "+str(array_num))
num_list = array_num.tolist()
print("la liste convertit:")
print(num_list)


tableau donnés: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
la liste convertit:
[1, 3, 5, 3, 7, 1, 9, 3]


In [7]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("sum of the diagonal elements:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
sum of the diagonal elements:
4


In [12]:
import numpy as np
x = np.array([[1, 2], [3, 5]])
print("Original array: ")
print(x)
print("Values bigger than 2 =", x[x>2])


Original array: 
[[1 2]
 [3 5]]
Values bigger than 2 = [3 5]


In [19]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
A=np.add(x, y)
print(A)

[[ 6.  8.]
 [10. 12.]]


In [14]:
import numpy as np
a = np.random.rand(3, 4)
print(a)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[0.08736829 0.61108293 0.02817937 0.78627058]
 [0.295829   0.24593129 0.58536616 0.1413822 ]
 [0.32243988 0.18473398 0.10455644 0.19741967]]
[[-0.290857    0.23285763 -0.35004592  0.40804529]
 [-0.02129816 -0.07119588  0.268239   -0.17574496]
 [ 0.12015239 -0.01755351 -0.09773105 -0.00486782]]
